Web/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Mvc;
using Service.Interfaces;

namespace Web.Controllers;

public class DashboardController: Controller
{
    private readonly IAuthService _authService;
    private readonly IUserService _userService;
    public DashboardController(IAuthService authService, IUserService userService)
    {
        _authService = authService;
        _userService = userService;
    }

    [HttpGet]
    public IActionResult Index()
    {
        return View();
    }
}

Web/Controllers/ProfileController.cs
using Microsoft.AspNetCore.Mvc;
using Repository.ViewModel;
using Service.Interfaces;

namespace Web.Controllers;

public class ProfileController : Controller
{
    private readonly IUserService _userService;
    public ProfileController(IUserService userService)
    {
        _userService = userService;
    }

    [HttpGet]
    public IActionResult Profile()
    {
        var token = Request.Cookies["Token"];
        var email = _userService.GetEmailFromToken(token);

        if (string.IsNullOrEmpty(email))
        {
            return RedirectToAction("Login", "Login");
        }

        var model = _userService.GetUserProfile(email);

        if (model == null)
        {
            return NotFound("User Not Found");
        }

        return View(model);
    }

    [HttpPost]
    public IActionResult Profile(UserViewModel model)
    {
        var token = Request.Cookies["Token"];
        var email = _userService.GetEmailFromToken(token);

        if (string.IsNullOrEmpty(email))
        {
            return RedirectToAction("Login", "Login");
        }

        var success = _userService.UpdateUserProfile(email, model);

        if (!success)
        {
            return NotFound("User Not Found");
        }

        TempData["success"] = "Profile updated successfully.";
        return View(model);
    }

    [HttpGet]
    public IActionResult ProfileChangePassword()
    {
        return View();
    }

    [HttpPost]
    public IActionResult ProfileChangePassword(ProfileChangePasswordViewModel model)
    {
        if (ModelState.IsValid)
        {
            var token = Request.Cookies["Token"];
            var userEmail = _userService.GetEmailFromToken(token);

            if (string.IsNullOrEmpty(userEmail))
            {
                return RedirectToAction("Login", "Login");
            }

            var result = _userService.ChangePassword(userEmail, model);

            if (result == "UserNotFound")
            {
                TempData["error"] = "User not found.";
                return View(model);
            }

            if (result == "IncorrectPassword")
            {
                TempData["error"] = "Current password is incorrect.";
                return View(model);
            }

            TempData["success"] = "Password updated successfully.";
            return RedirectToAction("Login", "Login");
        }
        return View();

    }
}

Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    @* <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" /> *@
    <link rel="stylesheet" href="~/css/style.css" asp-append-version="true" />
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
</head>

<body>
    <div class="main">
        <div class="offcanvas offcanvas-start d-lg-block show" tabindex="-1" id="sidebar" data-bs-scroll="true"
            data-bs-backdrop="false" aria-controls="offcanvasScrolling">

            <div class="offcanvas-body">
                <div class="d-flex align-items-center justify-content-center">
                    <img class="img-fluid pizza_shop_logo" src="~/images/logos/pizzashop_logo.png"
                        alt="Pizza shop logo not found">
                    <div class="title fs-5 fw-bold">PIZZASHOP</div>
                    <button type="button" class="btn-close d-md-none" data-bs-dismiss="offcanvas"
                        aria-label="Close"></button>
                </div>
                <div class="d-flex flex-column mt-3 ps-3">
                    <a asp-controller="Dashboard" asp-action="Index" class="dashboard_btn sidebar_btn mt-4 fw-bold d-flex align-items-center">
                        <img class="me-1" src="~/images/icons/border-all.svg" alt="Dashboard image not found">
                        <div>Dashboard</div>
                    </a>
                    <a asp-controller="User" asp-action="UserList" class="users_btn sidebar_btn mt-4 fw-bold d-flex align-items-center">
                        <img class="me-1" src="~/images/icons/people.svg" alt="">
                        <div>Users</div>
                    </a>
                    <a asp-controller="User" asp-action="Roles" class="role_permission_btn sidebar_btn mt-4 fw-bold d-flex align-items-center">
                        <img class="me-1" src="~/images/icons/person-gear.svg" alt="">
                        <div>Role and Permission</div>
                    </a>
                    <a asp-controller="Menu" asp-action="Menu" class="menu_btn sidebar_btn mt-4 fw-bold d-flex align-items-center">
                        <img class="me-1" src="~/images/icons/clipboard.svg" alt="">
                        <div>Menu</div>
                    </a>
                    <a href="" class="table_section_btn sidebar_btn mt-4 fw-bold d-flex align-items-center">
                        <img class="me-1" src="~/images/icons/square.svg" alt="">
                        <div>Table and Section</div>
                    </a>
                    <a href="" class="taxes_fees_btn sidebar_btn mt-4 fw-bold d-flex align-items-center">
                        <img class="me-1" src="~/images/icons/cash-coin.svg" alt="">
                        <div>Taxes And Fees</div>
                    </a>
                    <a href="" class="orders_btn sidebar_btn mt-4 fw-bold d-flex align-items-center">
                        <img class="me-1" src="~/images/icons/clipboard-check.svg" alt="">
                        <div>Orders</div>
                    </a>
                    <a href="" class="customers_btn sidebar_btn mt-4 fw-bold d-flex align-items-center">
                        <img class="me-1" src="~/images/icons/person-rolodex.svg" alt="">
                        <div>Customers</div>
                    </a>
                </div>
            </div>
        </div>
    </div>

    <div id="user_body">
        <div class="status d-flex align-items-center justify-content-between h-10">
            <a class="btn btn-primary bg-white d-lg-block toggle_btn" data-bs-toggle="offcanvas" href="#sidebar"
                role="button" aria-controls="sidebar">
                <div class="d-flex align-items-center justify-content-center">
                    <img class="img-fluid pizza_shop_logo" src="~/images/logos/pizzashop_logo.png"
                        alt="Pizza shop logo not found">
                    @* <div class="title fs-5 fw-bold">PIZZASHOP</div> *@
                </div>
            </a>
            <div>
                <img class=" dropdown-toggle me-2 rounded-circle" data-bs-toggle="dropdown" aria-expanded="false" width="30" height="30"
                    src="@Context.Request.Cookies["Image"]" alt="">
                <ul class="dropdown-menu dropdown-menu-end ">
                    <li><a class="dropdown-item d-flex align-items-center" href="#">
                            <img class="me-2 rounded-circle" width="30" height="30" src="@Context.Request.Cookies["Image"]" alt="">
                            @Context.Request.Cookies["Username"]</a>
                        </a></li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>
                    <li>
                        <a class="dropdown-item d-flex align-items-center" asp-controller="Profile" asp-action="Profile">
                            <img class="me-2 rounded-circle" width="30" height="30" src="@Context.Request.Cookies["Image"]" alt="">
                            My profile
                        </a>
                    </li>
                    <li><a class="dropdown-item d-flex align-items-center" asp-controller="Profile"
                            asp-action="ProfileChangePassword">
                            Change Password
                        </a></li>
                    <li><a class="dropdown-item d-flex align-items-center" asp-controller="Profile" asp-action="Logout"
                            data-bs-toggle="modal" data-bs-target="#logout">
                            <div class="d-flex">
                                Logout
                            </div>
                        </a></li>
                </ul>
            </div>
        </div>

        <div class="modal fade" id="logout" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered justify-content-center">
                <form>
                    <div class="modal-content">
                        <div class="modal-body">
                            <div class="d-flex justify-content-center"><img class="alert_img w-50"
                            width="100px" height="100px"
                                    src="~/images/toppng.com-warning-icon-2400x2400.png" alt=""></div>
                            <div class="d-flex justify-content-center">Are you sure you want to logout?
                            </div>
                        </div>
                        <div class="modal-footer d-flex justify-content-center">
                            <div class=" mt-3">
                                <button type="submit" asp-controller="Login" asp-action="Logout"
                                    class="btn btn-primary">Yes</button>
                                <button type="submit" class="btn border-primary ms-1">No</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <partial name="_Toaster.cshtml" ></partial>
        @RenderBody()

    </div>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>

Web/Views/Shared/_LayoutMain.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Users</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    @* <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" /> *@
    <link rel="stylesheet" href="~/css/style.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/test.styles.css" asp-append-version="true" />
</head>

<body>
    <div class="main">
        <div class="offcanvas offcanvas-start d-lg-block show" tabindex="-1" id="sidebar" data-bs-scroll="true"
            data-bs-backdrop="false" aria-controls="offcanvasScrolling">

            <div class="offcanvas-body">
                <div class="d-flex align-items-center justify-content-center">
                    <img class="img-fluid pizza_shop_logo" src="~/images/logos/pizzashop_logo.png"
                        alt="Pizza shop logo not found">
                    <div class="title fs-5 fw-bold">PIZZASHOP</div>
                    <button type="button" class="btn-close d-md-none" data-bs-dismiss="offcanvas"
                        aria-label="Close"></button>
                </div>
                <div class="d-flex flex-column mt-3 ps-3">
                    <a href="" class="dashboard_btn sidebar_btn d-flex align-items-center">
                        <img class="me-2" src="~/images/Download/border-all.svg" alt="Dashboard image not found">
                        <div>Dashboard</div>
                    </a>
                    <a asp-controller="Home" asp-action="UserList" class="users_btn d-flex sidebar_btn">
                        <img src="~/images/Download/people.svg" alt="">
                        <div>Users</div>
                    </a>
                    <a asp-controller="Home" asp-action="Role" class="role_permission_btn d-flex sidebar_btn">
                        <img src="~/images/Download/person-fill-gear.svg" alt="">
                        <div>Role and Permission</div>
                    </a>
                    <a href="menu.html" class="menu_btn sidebar_btn">
                        <img src="~/images/Download/border-all.svg" alt="">
                        <div>Menu</div>
                    </a>
                    <a href="" class="table_section_btn sidebar_btn">
                        <img src="" alt="">
                        <div>Table and Section</div>
                    </a>
                    <a href="" class="taxes_fees_btn sidebar_btn">
                        <img src="" alt="">
                        <div>Taxes And Fees</div>
                    </a>
                    <a href="" class="orders_btn sidebar_btn">
                        <img src="" alt="">
                        <div>Orders</div>
                    </a>
                    <a href="" class="customers_btn sidebar_btn">
                        <img src="" alt="">
                        <div>Customers</div>
                    </a>
                </div>
            </div>
        </div>
    </div>

    <div id="user_body">
        <div class="status d-flex align-items-center justify-content-between h-10">
            <a class="btn btn-primary bg-white d-lg-block" data-bs-toggle="offcanvas" href="#sidebar" role="button"
                aria-controls="sidebar">
                <div class="d-flex align-items-center justify-content-center">
                    <img class="img-fluid pizza_shop_logo" src="~/images/logos/pizzashop_logo.png"
                        alt="Pizza shop logo not found">
                    <div class="title fs-5 fw-bold">PIZZASHOP</div>
                </div>
            </a>
            <div>
                <img class=" dropdown-toggle me-2" data-bs-toggle="dropdown" aria-expanded="false" width="35"
                    src="~/images/Default_pfp.svg.png" alt="">
                <ul class="dropdown-menu dropdown-menu-end ">
                    <li><a class="dropdown-item d-flex align-items-center" href="#">
                            <img class="me-2" width="25" src="~/images/Default_pfp.svg.png" alt="">
                            @Model.Username</p>
                        </a></li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>
                    <li>
                        <a class="dropdown-item d-flex align-items-center" asp-controller="Home" asp-action="Profile">
                            <img class="me-2" width="25" src="~/images/Default_pfp.svg.png" alt="">
                            My profile
                        </a>
                    </li>
                    <li><a class="dropdown-item d-flex align-items-center" asp-controller="Home"
                            asp-action="ProfileChangePassword">
                            Change Password
                        </a></li>
                    <li><a class="dropdown-item d-flex align-items-center" asp-controller="Home" asp-action="Logout"
                            data-bs-toggle="modal" data-bs-target="#exampleModal">
                            <div class="d-flex">
                                Logout
                            </div>
                        </a></li>
                </ul>
            </div>
        </div>

        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered">
                <form>
                    <div class="modal-content">
                        <div class="modal-body">
                            <div class="d-flex justify-content-center"><img class="alert_img w-50"
                                    src="~/images/toppng.com-warning-icon-2400x2400.png" alt=""></div>
                            <div class="d-flex justify-content-center">Are you sure you want to logout?
                            </div>
                        </div>
                        <div class="modal-footer d-flex justify-content-center">
                            <div class=" mt-3">
                                <button type="submit" asp-controller="Home" asp-action="Logout"
                                    class="btn btn-primary">Yes</button>
                                <button type="submit" class="btn border-primary ms-1">No</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        @RenderBody
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="script.js"></script>
</body>

</html>

Web/Views/Shared/_Toaster.cshtml
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js" integrity="sha512-VEd+nq25CkR676O+pLBnDW09R7VQX9Mdiij052gVCp5yVH3jGtH70Ho/UUv4mJDsEdTvqRCFZg0NKGiojGnUCw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
 <link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" rel="stylesheet" />
<script type="text/javascript">
    // Set Toastr options globally
    toastr.options = {
        "closeButton": true, // Show close button
        "debug": false,
        "newestOnTop": true,
        "progressBar": true,
        "positionClass": "toast-top-right", // Position of toast
        "preventDuplicates": true,
        "showDuration": "300",
        "hideDuration": "1000",
        "timeOut": "5000", // Toast will disappear after 5 seconds
        "extendedTimeOut": "1000",
        "showEasing": "swing",
        "hideEasing": "linear",
        "showMethod": "fadeIn",
        "hideMethod": "fadeOut"
    };

    // Display the toast message
    @if (TempData["error"] != null)
    {
        <text>
            toastr.error('@TempData["error"]');
        </text>
    }

    @if (TempData["success"] != null)
    {
        <text>
            toastr.success('@TempData["success"]');
        </text>
    }
</script>